/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStorybookRouteImport } from './routes/demo/storybook'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChartsRouteImport } from './routes/_authenticated/charts'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedHelpCenterLayoutRouteImport } from './routes/_authenticated/help-center/_layout'
import { Route as AuthenticatedauthProfileRouteImport } from './routes/_authenticated/(auth)/profile'
import { Route as AuthenticatedHelpCenterLayoutIndexRouteImport } from './routes/_authenticated/help-center/_layout/index'
import { Route as AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteImport } from './routes/_authenticated/help-center/_layout/topic_section/_layout'
import { Route as AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteImport } from './routes/_authenticated/help-center/_layout/topic_category/_layout'
import { Route as AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteImport } from './routes/_authenticated/help-center/_layout/topic_article/_layout'
import { Route as AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRouteImport } from './routes/_authenticated/help-center/_layout/topic_section/_layout/index'
import { Route as AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRouteImport } from './routes/_authenticated/help-center/_layout/topic_category/_layout/index'
import { Route as AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRouteImport } from './routes/_authenticated/help-center/_layout/topic_article/_layout/index'
import { Route as AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRouteImport } from './routes/_authenticated/help-center/_layout/topic_section/_layout/$id'
import { Route as AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRouteImport } from './routes/_authenticated/help-center/_layout/topic_category/_layout/$id'
import { Route as AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRouteImport } from './routes/_authenticated/help-center/_layout/topic_article/_layout/$id'

const AuthenticatedHelpCenterRouteImport = createFileRoute(
  '/_authenticated/help-center',
)()
const errors503LazyRouteImport = createFileRoute('/(errors)/503')()
const errors500LazyRouteImport = createFileRoute('/(errors)/500')()
const errors404LazyRouteImport = createFileRoute('/(errors)/404')()
const errors403LazyRouteImport = createFileRoute('/(errors)/403')()
const errors401LazyRouteImport = createFileRoute('/(errors)/401')()
const authSigninLazyRouteImport = createFileRoute('/(auth)/signin')()
const authSignUpLazyRouteImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyRouteImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyRouteImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedHelpCenterLayoutTopic_sectionRouteImport = createFileRoute(
  '/_authenticated/help-center/_layout/topic_section',
)()
const AuthenticatedHelpCenterLayoutTopic_categoryRouteImport = createFileRoute(
  '/_authenticated/help-center/_layout/topic_category',
)()
const AuthenticatedHelpCenterLayoutTopic_articleRouteImport = createFileRoute(
  '/_authenticated/help-center/_layout/topic_article',
)()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHelpCenterRoute = AuthenticatedHelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const errors503LazyRoute = errors503LazyRouteImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))
const errors500LazyRoute = errors500LazyRouteImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))
const errors404LazyRoute = errors404LazyRouteImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))
const errors403LazyRoute = errors403LazyRouteImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))
const errors401LazyRoute = errors401LazyRouteImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))
const authSigninLazyRoute = authSigninLazyRouteImport
  .update({
    id: '/(auth)/signin',
    path: '/signin',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/signin.lazy').then((d) => d.Route))
const authSignUpLazyRoute = authSignUpLazyRouteImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))
const authSignIn2LazyRoute = authSignIn2LazyRouteImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))
const authForgotPasswordLazyRoute = authForgotPasswordLazyRouteImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStorybookRoute = DemoStorybookRouteImport.update({
  id: '/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChartsRoute = AuthenticatedChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterLayoutRoute =
  AuthenticatedHelpCenterLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedHelpCenterRoute,
  } as any)
const AuthenticatedauthProfileRoute =
  AuthenticatedauthProfileRouteImport.update({
    id: '/(auth)/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_sectionRoute =
  AuthenticatedHelpCenterLayoutTopic_sectionRouteImport.update({
    id: '/topic_section',
    path: '/topic_section',
    getParentRoute: () => AuthenticatedHelpCenterLayoutRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_categoryRoute =
  AuthenticatedHelpCenterLayoutTopic_categoryRouteImport.update({
    id: '/topic_category',
    path: '/topic_category',
    getParentRoute: () => AuthenticatedHelpCenterLayoutRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_articleRoute =
  AuthenticatedHelpCenterLayoutTopic_articleRouteImport.update({
    id: '/topic_article',
    path: '/topic_article',
    getParentRoute: () => AuthenticatedHelpCenterLayoutRoute,
  } as any)
const AuthenticatedHelpCenterLayoutIndexRoute =
  AuthenticatedHelpCenterLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHelpCenterLayoutRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_sectionLayoutRoute =
  AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedHelpCenterLayoutTopic_sectionRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_categoryLayoutRoute =
  AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedHelpCenterLayoutTopic_categoryRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_articleLayoutRoute =
  AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedHelpCenterLayoutTopic_articleRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRoute =
  AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHelpCenterLayoutTopic_sectionLayoutRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRoute =
  AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedHelpCenterLayoutTopic_categoryLayoutRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRoute =
  AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHelpCenterLayoutTopic_articleLayoutRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRoute =
  AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedHelpCenterLayoutTopic_sectionLayoutRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRoute =
  AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () =>
      AuthenticatedHelpCenterLayoutTopic_categoryLayoutRoute,
  } as any)
const AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRoute =
  AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedHelpCenterLayoutTopic_articleLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/signin': typeof authSigninLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/profile': typeof AuthenticatedauthProfileRoute
  '/help-center': typeof AuthenticatedHelpCenterLayoutRouteWithChildren
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterLayoutIndexRoute
  '/help-center/topic_article': typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteWithChildren
  '/help-center/topic_category': typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteWithChildren
  '/help-center/topic_section': typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteWithChildren
  '/help-center/topic_article/$id': typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRoute
  '/help-center/topic_category/$id': typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRoute
  '/help-center/topic_section/$id': typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRoute
  '/help-center/topic_article/': typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRoute
  '/help-center/topic_category/': typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRoute
  '/help-center/topic_section/': typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/signin': typeof authSigninLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/profile': typeof AuthenticatedauthProfileRoute
  '/help-center': typeof AuthenticatedHelpCenterLayoutIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/help-center/topic_article': typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRoute
  '/help-center/topic_category': typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRoute
  '/help-center/topic_section': typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRoute
  '/help-center/topic_article/$id': typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRoute
  '/help-center/topic_category/$id': typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRoute
  '/help-center/topic_section/$id': typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/charts': typeof AuthenticatedChartsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/demo/storybook': typeof DemoStorybookRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(auth)/signin': typeof authSigninLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/(auth)/profile': typeof AuthenticatedauthProfileRoute
  '/_authenticated/help-center': typeof AuthenticatedHelpCenterRouteWithChildren
  '/_authenticated/help-center/_layout': typeof AuthenticatedHelpCenterLayoutRouteWithChildren
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/help-center/_layout/': typeof AuthenticatedHelpCenterLayoutIndexRoute
  '/_authenticated/help-center/_layout/topic_article': typeof AuthenticatedHelpCenterLayoutTopic_articleRouteWithChildren
  '/_authenticated/help-center/_layout/topic_article/_layout': typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteWithChildren
  '/_authenticated/help-center/_layout/topic_category': typeof AuthenticatedHelpCenterLayoutTopic_categoryRouteWithChildren
  '/_authenticated/help-center/_layout/topic_category/_layout': typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteWithChildren
  '/_authenticated/help-center/_layout/topic_section': typeof AuthenticatedHelpCenterLayoutTopic_sectionRouteWithChildren
  '/_authenticated/help-center/_layout/topic_section/_layout': typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteWithChildren
  '/_authenticated/help-center/_layout/topic_article/_layout/$id': typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRoute
  '/_authenticated/help-center/_layout/topic_category/_layout/$id': typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRoute
  '/_authenticated/help-center/_layout/topic_section/_layout/$id': typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRoute
  '/_authenticated/help-center/_layout/topic_article/_layout/': typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRoute
  '/_authenticated/help-center/_layout/topic_category/_layout/': typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRoute
  '/_authenticated/help-center/_layout/topic_section/_layout/': typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/otp'
    | '/sign-in'
    | '/charts'
    | '/dashboard'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/signin'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/profile'
    | '/help-center'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/settings/'
    | '/help-center/'
    | '/help-center/topic_article'
    | '/help-center/topic_category'
    | '/help-center/topic_section'
    | '/help-center/topic_article/$id'
    | '/help-center/topic_category/$id'
    | '/help-center/topic_section/$id'
    | '/help-center/topic_article/'
    | '/help-center/topic_category/'
    | '/help-center/topic_section/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/otp'
    | '/sign-in'
    | '/charts'
    | '/dashboard'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/signin'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/profile'
    | '/help-center'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/settings'
    | '/help-center/topic_article'
    | '/help-center/topic_category'
    | '/help-center/topic_section'
    | '/help-center/topic_article/$id'
    | '/help-center/topic_category/$id'
    | '/help-center/topic_section/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_authenticated/charts'
    | '/_authenticated/dashboard'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/signin'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/(auth)/profile'
    | '/_authenticated/help-center'
    | '/_authenticated/help-center/_layout'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/_authenticated/settings/'
    | '/_authenticated/help-center/_layout/'
    | '/_authenticated/help-center/_layout/topic_article'
    | '/_authenticated/help-center/_layout/topic_article/_layout'
    | '/_authenticated/help-center/_layout/topic_category'
    | '/_authenticated/help-center/_layout/topic_category/_layout'
    | '/_authenticated/help-center/_layout/topic_section'
    | '/_authenticated/help-center/_layout/topic_section/_layout'
    | '/_authenticated/help-center/_layout/topic_article/_layout/$id'
    | '/_authenticated/help-center/_layout/topic_category/_layout/$id'
    | '/_authenticated/help-center/_layout/topic_section/_layout/$id'
    | '/_authenticated/help-center/_layout/topic_article/_layout/'
    | '/_authenticated/help-center/_layout/topic_category/_layout/'
    | '/_authenticated/help-center/_layout/topic_section/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  DemoStorybookRoute: typeof DemoStorybookRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  authSigninLazyRoute: typeof authSigninLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/help-center': {
      id: '/_authenticated/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/storybook': {
      id: '/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof DemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/charts': {
      id: '/_authenticated/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AuthenticatedChartsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/_layout': {
      id: '/_authenticated/help-center/_layout'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutRouteImport
      parentRoute: typeof AuthenticatedHelpCenterRoute
    }
    '/_authenticated/(auth)/profile': {
      id: '/_authenticated/(auth)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedauthProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help-center/_layout/topic_section': {
      id: '/_authenticated/help-center/_layout/topic_section'
      path: '/topic_section'
      fullPath: '/help-center/topic_section'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutRoute
    }
    '/_authenticated/help-center/_layout/topic_category': {
      id: '/_authenticated/help-center/_layout/topic_category'
      path: '/topic_category'
      fullPath: '/help-center/topic_category'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutRoute
    }
    '/_authenticated/help-center/_layout/topic_article': {
      id: '/_authenticated/help-center/_layout/topic_article'
      path: '/topic_article'
      fullPath: '/help-center/topic_article'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutRoute
    }
    '/_authenticated/help-center/_layout/': {
      id: '/_authenticated/help-center/_layout/'
      path: '/'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutRoute
    }
    '/_authenticated/help-center/_layout/topic_section/_layout': {
      id: '/_authenticated/help-center/_layout/topic_section/_layout'
      path: '/topic_section'
      fullPath: '/help-center/topic_section'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionRoute
    }
    '/_authenticated/help-center/_layout/topic_category/_layout': {
      id: '/_authenticated/help-center/_layout/topic_category/_layout'
      path: '/topic_category'
      fullPath: '/help-center/topic_category'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryRoute
    }
    '/_authenticated/help-center/_layout/topic_article/_layout': {
      id: '/_authenticated/help-center/_layout/topic_article/_layout'
      path: '/topic_article'
      fullPath: '/help-center/topic_article'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleRoute
    }
    '/_authenticated/help-center/_layout/topic_section/_layout/': {
      id: '/_authenticated/help-center/_layout/topic_section/_layout/'
      path: '/'
      fullPath: '/help-center/topic_section/'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutRoute
    }
    '/_authenticated/help-center/_layout/topic_category/_layout/': {
      id: '/_authenticated/help-center/_layout/topic_category/_layout/'
      path: '/'
      fullPath: '/help-center/topic_category/'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutRoute
    }
    '/_authenticated/help-center/_layout/topic_article/_layout/': {
      id: '/_authenticated/help-center/_layout/topic_article/_layout/'
      path: '/'
      fullPath: '/help-center/topic_article/'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutRoute
    }
    '/_authenticated/help-center/_layout/topic_section/_layout/$id': {
      id: '/_authenticated/help-center/_layout/topic_section/_layout/$id'
      path: '/$id'
      fullPath: '/help-center/topic_section/$id'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutRoute
    }
    '/_authenticated/help-center/_layout/topic_category/_layout/$id': {
      id: '/_authenticated/help-center/_layout/topic_category/_layout/$id'
      path: '/$id'
      fullPath: '/help-center/topic_category/$id'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutRoute
    }
    '/_authenticated/help-center/_layout/topic_article/_layout/$id': {
      id: '/_authenticated/help-center/_layout/topic_article/_layout/$id'
      path: '/$id'
      fullPath: '/help-center/topic_article/$id'
      preLoaderRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRouteImport
      parentRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteChildren {
  AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRoute
  AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRoute
}

const AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteChildren: AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteChildren =
  {
    AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRoute:
      AuthenticatedHelpCenterLayoutTopic_articleLayoutIdRoute,
    AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRoute:
      AuthenticatedHelpCenterLayoutTopic_articleLayoutIndexRoute,
  }

const AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteWithChildren =
  AuthenticatedHelpCenterLayoutTopic_articleLayoutRoute._addFileChildren(
    AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteChildren,
  )

interface AuthenticatedHelpCenterLayoutTopic_articleRouteChildren {
  AuthenticatedHelpCenterLayoutTopic_articleLayoutRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteWithChildren
}

const AuthenticatedHelpCenterLayoutTopic_articleRouteChildren: AuthenticatedHelpCenterLayoutTopic_articleRouteChildren =
  {
    AuthenticatedHelpCenterLayoutTopic_articleLayoutRoute:
      AuthenticatedHelpCenterLayoutTopic_articleLayoutRouteWithChildren,
  }

const AuthenticatedHelpCenterLayoutTopic_articleRouteWithChildren =
  AuthenticatedHelpCenterLayoutTopic_articleRoute._addFileChildren(
    AuthenticatedHelpCenterLayoutTopic_articleRouteChildren,
  )

interface AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteChildren {
  AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRoute
  AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRoute
}

const AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteChildren: AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteChildren =
  {
    AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRoute:
      AuthenticatedHelpCenterLayoutTopic_categoryLayoutIdRoute,
    AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRoute:
      AuthenticatedHelpCenterLayoutTopic_categoryLayoutIndexRoute,
  }

const AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteWithChildren =
  AuthenticatedHelpCenterLayoutTopic_categoryLayoutRoute._addFileChildren(
    AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteChildren,
  )

interface AuthenticatedHelpCenterLayoutTopic_categoryRouteChildren {
  AuthenticatedHelpCenterLayoutTopic_categoryLayoutRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteWithChildren
}

const AuthenticatedHelpCenterLayoutTopic_categoryRouteChildren: AuthenticatedHelpCenterLayoutTopic_categoryRouteChildren =
  {
    AuthenticatedHelpCenterLayoutTopic_categoryLayoutRoute:
      AuthenticatedHelpCenterLayoutTopic_categoryLayoutRouteWithChildren,
  }

const AuthenticatedHelpCenterLayoutTopic_categoryRouteWithChildren =
  AuthenticatedHelpCenterLayoutTopic_categoryRoute._addFileChildren(
    AuthenticatedHelpCenterLayoutTopic_categoryRouteChildren,
  )

interface AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteChildren {
  AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRoute
  AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRoute
}

const AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteChildren: AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteChildren =
  {
    AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRoute:
      AuthenticatedHelpCenterLayoutTopic_sectionLayoutIdRoute,
    AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRoute:
      AuthenticatedHelpCenterLayoutTopic_sectionLayoutIndexRoute,
  }

const AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteWithChildren =
  AuthenticatedHelpCenterLayoutTopic_sectionLayoutRoute._addFileChildren(
    AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteChildren,
  )

interface AuthenticatedHelpCenterLayoutTopic_sectionRouteChildren {
  AuthenticatedHelpCenterLayoutTopic_sectionLayoutRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteWithChildren
}

const AuthenticatedHelpCenterLayoutTopic_sectionRouteChildren: AuthenticatedHelpCenterLayoutTopic_sectionRouteChildren =
  {
    AuthenticatedHelpCenterLayoutTopic_sectionLayoutRoute:
      AuthenticatedHelpCenterLayoutTopic_sectionLayoutRouteWithChildren,
  }

const AuthenticatedHelpCenterLayoutTopic_sectionRouteWithChildren =
  AuthenticatedHelpCenterLayoutTopic_sectionRoute._addFileChildren(
    AuthenticatedHelpCenterLayoutTopic_sectionRouteChildren,
  )

interface AuthenticatedHelpCenterLayoutRouteChildren {
  AuthenticatedHelpCenterLayoutIndexRoute: typeof AuthenticatedHelpCenterLayoutIndexRoute
  AuthenticatedHelpCenterLayoutTopic_articleRoute: typeof AuthenticatedHelpCenterLayoutTopic_articleRouteWithChildren
  AuthenticatedHelpCenterLayoutTopic_categoryRoute: typeof AuthenticatedHelpCenterLayoutTopic_categoryRouteWithChildren
  AuthenticatedHelpCenterLayoutTopic_sectionRoute: typeof AuthenticatedHelpCenterLayoutTopic_sectionRouteWithChildren
}

const AuthenticatedHelpCenterLayoutRouteChildren: AuthenticatedHelpCenterLayoutRouteChildren =
  {
    AuthenticatedHelpCenterLayoutIndexRoute:
      AuthenticatedHelpCenterLayoutIndexRoute,
    AuthenticatedHelpCenterLayoutTopic_articleRoute:
      AuthenticatedHelpCenterLayoutTopic_articleRouteWithChildren,
    AuthenticatedHelpCenterLayoutTopic_categoryRoute:
      AuthenticatedHelpCenterLayoutTopic_categoryRouteWithChildren,
    AuthenticatedHelpCenterLayoutTopic_sectionRoute:
      AuthenticatedHelpCenterLayoutTopic_sectionRouteWithChildren,
  }

const AuthenticatedHelpCenterLayoutRouteWithChildren =
  AuthenticatedHelpCenterLayoutRoute._addFileChildren(
    AuthenticatedHelpCenterLayoutRouteChildren,
  )

interface AuthenticatedHelpCenterRouteChildren {
  AuthenticatedHelpCenterLayoutRoute: typeof AuthenticatedHelpCenterLayoutRouteWithChildren
}

const AuthenticatedHelpCenterRouteChildren: AuthenticatedHelpCenterRouteChildren =
  {
    AuthenticatedHelpCenterLayoutRoute:
      AuthenticatedHelpCenterLayoutRouteWithChildren,
  }

const AuthenticatedHelpCenterRouteWithChildren =
  AuthenticatedHelpCenterRoute._addFileChildren(
    AuthenticatedHelpCenterRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedChartsRoute: typeof AuthenticatedChartsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedauthProfileRoute: typeof AuthenticatedauthProfileRoute
  AuthenticatedHelpCenterRoute: typeof AuthenticatedHelpCenterRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedChartsRoute: AuthenticatedChartsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedauthProfileRoute: AuthenticatedauthProfileRoute,
  AuthenticatedHelpCenterRoute: AuthenticatedHelpCenterRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  DemoStorybookRoute: DemoStorybookRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  authSigninLazyRoute: authSigninLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
